WebSurvey_Sales_CRM/Areas/Admin/Controllers/NewOptionController.cs
using Microsoft.AspNetCore.Mvc;
using WebSurvey_Sales_CRM.Areas.Admin.Reponsitory.Interface;
using WebSurvey_Sales_CRM.Models;

namespace WebSurvey_Sales_CRM.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewOptionController : Controller
    {
        public readonly INewOption _newOptionRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public NewOptionController(INewOption newOptionRepository, IHttpContextAccessor httpContextAccessor)
        {
            _newOptionRepository = newOptionRepository;
            _httpContextAccessor = httpContextAccessor;

        }
        /*-------------------------------------------------- Roles --------------------------------------------------*/
        //Get all data in table Roles User
        [HttpGet]
        public async Task<IActionResult> IndexRoles()
        {
            try
            {
                var data = await _newOptionRepository.GetRoles();
                return View(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        
        //Add one row data in Roles User
        [HttpPost]
        public async Task<IActionResult> IndexRoles(RolesUser rolesUser)
        {
            try
            {
                await _newOptionRepository.AddNameRoles(rolesUser);
                return await IndexRoles();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //View Delete
        [HttpGet]
        public async Task<IActionResult> DeleteRoles(int id)
        {
            try
            {
                var data = await _newOptionRepository.GetDeleteNameRoles(id);
                return View(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //Delete one row data in Roles User

        [HttpPost, ActionName("DeleteRoles")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedRoles(int id)
        {
            try
            {
                await _newOptionRepository.DeleteNameRoles(id);

                return Redirect("/admin/newoption/indexroles");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }

/*-------------------------------------------------- Source --------------------------------------------------*/
        //Get all data in table Source
        [HttpGet]
        public async Task<IActionResult> IndexSource()
        {
            try
            {
                if (_httpContextAccessor.HttpContext?.Session.GetInt32("idUser") == null)
                {
                    return Redirect("/");
                }
                var data = await _newOptionRepository.GetSource();
                return View(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //Add one row data in Roles User
        [HttpPost]
        public async Task<IActionResult> IndexSource(Source source)
        {
            try
            {
                await _newOptionRepository.AddNameSource(source);
                return await IndexSource();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //View Delete
        [HttpGet]
        public async Task<IActionResult> DeleteSource(int id)
        {
            try
            {
                if (_httpContextAccessor.HttpContext?.Session.GetInt32("idUser") == null)
                {
                    return Redirect("/");
                }
                var data = await _newOptionRepository.GetDeleteNameSource(id);
                return View(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //Delete one row data in Roles User

        [HttpPost, ActionName("DeleteSource")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedSource(int id)
        {
            try
            {
                await _newOptionRepository.DeleteNameSource(id);

                return Redirect("/admin/newoption/indexsource");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }

/*-------------------------------------------------- Team --------------------------------------------------*/
        //Get all data in table Team
        [HttpGet]
        public async Task<IActionResult> IndexTeam()
        {
            try
            {
                if (_httpContextAccessor.HttpContext?.Session.GetInt32("idUser") == null)
                {
                    return Redirect("/");
                }
                var data = await _newOptionRepository.GetTeam();
                return View(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //Add one row data in Team
        [HttpPost]
        public async Task<IActionResult> IndexTeam(Team team)
        {
            try
            {
                await _newOptionRepository.AddNameTeam(team);
                return await IndexTeam();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //View Delete
        [HttpGet]
        public async Task<IActionResult> DeleteTeam(int id)
        {
            try
            {
                if (_httpContextAccessor.HttpContext?.Session.GetInt32("idUser") == null)
                {
                    return Redirect("/");
                }
                var data = await _newOptionRepository.GetDeleteNameTeam(id);
                return View(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
        //Delete one row data in Team

        [HttpPost, ActionName("DeleteTeam")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedTeam(int id)
        {
            try
            {
                await _newOptionRepository.DeleteNameTeam(id);

                return Redirect("/admin/newoption/indexteam");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return View();
            }
        }
    }
}

WebSurvey_Sales_CRM/Areas/Admin/Views/NewOption/DeleteRoles.cshtml
@model IEnumerable<WebSurvey_Sales_CRM.Models.RolesUser>

@{
    Layout = "_Layout";
}

<section class="text-center mt-5">
    <div class="card mx-auto" style="max-width: 400px;">
        <div class="card-header bg-danger text-white">
            <h3 class="card-title">Bạn có chắc bạn muốn xóa mục này?</h3>
        </div>
        <div class="card-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.NameRolesUser)
                </dt>
               @*  <dd>
                    @Html.DisplayFor(model => model.NameRolesUser)
                </dd> *@
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions">
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                    <a href="/admin/newoption/indexroles" class="btn btn-secondary">Quay lại</a>
                </div>
            }
        </div>
    </div>
</section>

WebSurvey_Sales_CRM/Areas/Admin/Views/NewOption/DeleteSource.cshtml
@model IEnumerable<WebSurvey_Sales_CRM.Models.Source>


@{
    Layout = "_Layout";
}

<section class="text-center mt-5">
    <div class="card mx-auto" style="max-width: 400px;">
        <div class="card-header bg-danger text-white">
            <h3 class="card-title">Bạn có chắc bạn muốn xóa mục này?</h3>
        </div>
        <div class="card-body">
            @foreach (var source in Model)
            {
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => source.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => source.Name)
                    </dd>
                </dl>
            }

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions">
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                    <a href="/admin/newoption/indexsource" class="btn btn-secondary">Quay lại</a>
                </div>
            }
        </div>
    </div>
</section>

WebSurvey_Sales_CRM/Areas/Admin/Views/NewOption/DeleteTeam.cshtml
@model IEnumerable<WebSurvey_Sales_CRM.Models.Team>


@{
    Layout = "_Layout";
}

<section class="text-center mt-5">
    <div class="card mx-auto" style="max-width: 400px;">
        <div class="card-header bg-danger text-white">
            <h3 class="card-title">Bạn có chắc bạn muốn xóa mục này?</h3>
        </div>
        <div class="card-body">
            @foreach (var team in Model)
            {
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => team.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => team.Name)
                    </dd>
                </dl>
            }

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions">
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                    <a href="/admin/newoption/indexteam" class="btn btn-secondary">Quay lại</a>
                </div>
            }
        </div>
    </div>
</section>

WebSurvey_Sales_CRM/Areas/Admin/Views/NewOption/IndexRoles.cshtml
@model IEnumerable<WebSurvey_Sales_CRM.Models.RolesUser>
@{
    Layout = "_Layout";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      integrity="sha512-Lp2FfY5eo5WDWDaz9i/J9Fj7sNmJfwClnLfqLz1/IrZ5kQDbQ0YiN3qI45hDcDkfLbG0vP2DjkDOO8n5sYF5kg=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="container bg-light">
    <div class="row">
        <div class="col-12 col-md-6">
            <h2>Quyền truy cập</h2>
            <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NameRolesUser</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.NameRolesUser</td>

                                <td>

                                   
                                    <a class="btn btn-sm btn-danger p-2" href="/admin/newoption/deleteroles/@item.Id">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>



                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="2">Không có quyền truy cập nào</td>
                        </tr>
                    }
                </tbody>
            </table>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <h2>Thêm quyền truy cập</h2>
            <hr />
            <form asp-controller="NewOption" asp-action="IndexRoles" method="post">
                

                <div class="form-group">
                    <input type="text" name="NameRolesUser" class="form-control" />
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>
    
</div>

WebSurvey_Sales_CRM/Areas/Admin/Views/NewOption/IndexSource.cshtml
@model IEnumerable<WebSurvey_Sales_CRM.Models.Source>
@{
    Layout = "_Layout";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      integrity="sha512-Lp2FfY5eo5WDWDaz9i/J9Fj7sNmJfwClnLfqLz1/IrZ5kQDbQ0YiN3qI45hDcDkfLbG0vP2DjkDOO8n5sYF5kg=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />
<body onload="generateSourceCode()">
<div class="container bg-light" >
    <div class="row">
            <div class="col-12 col-md-6">
            <h2>Nguồn</h2>
                <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>SourceCode</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.SourceCode</td>
                                <td>
                                   
                                        <a class="btn btn-sm btn-danger p-2" href="/admin/newoption/deletesource/@item.Id">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="2">Không có nguồn nào</td>
                        </tr>
                    }
                </tbody>
            </table>
                </div>
        </div>
            <div class="col-12 col-md-6">
            <h2>Thêm nguồn</h2>
            <hr />
            <form asp-controller="NewOption" asp-action="IndexSource" method="post" >
                <div class="form-group">
                    <input type="text" name="Name" class="form-control" placeholder="Vui lòng nhập tên nguồn" required />
                </div>  
                <div class="form-group">
                    <input type="hidden" name="SourceCode" id="sourceCodeInput" class="form-control" />   
                </div>
                <div class="form-group">
                    <button type="submit"class="btn btn-primary">Thêm</button>
                </div>
            </form>

        </div>
    </div>
    
</div>
</body>
<script>
    function generateSourceCode() {
        var sourceCodeInput = document.getElementById("sourceCodeInput");
        var generatedCode = generateUniqueCode();
        console.log("After setting value:", sourceCodeInput.value);
        sourceCodeInput.value = generatedCode;
    }

    var generatedCodes = [];

    function generateUniqueCode() {
        var min = 1;
        var max = 10000000;

        var uniqueCode;
        do {
            uniqueCode = Math.floor(Math.random() * (max - min + 1)) + min;
        } while (generatedCodes.includes(uniqueCode));

        generatedCodes.push(uniqueCode);

        return uniqueCode;
    }

</script>

WebSurvey_Sales_CRM/Areas/Admin/Views/NewOption/IndexTeam.cshtml
@model IEnumerable<WebSurvey_Sales_CRM.Models.Team>
@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      integrity="sha512-Lp2FfY5eo5WDWDaz9i/J9Fj7sNmJfwClnLfqLz1/IrZ5kQDbQ0YiN3qI45hDcDkfLbG0vP2DjkDOO8n5sYF5kg=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />

<body onload="generateSourceCode()">
<div class="container bg-light" >
    <div class="row">
            <div class="col-12 col-md-6">
            <h2>Nhóm</h2>
                <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>TeamCode</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.TeamCode</td>
                                <td>
                                   
                                        <a class="btn btn-sm btn-danger p-2" href="/admin/newoption/deleteteam/@item.Id">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="2">Không có nhóm nào</td>
                        </tr>
                    }
                </tbody>
            </table>
            </div>
        </div>
            <div class="col-12 col-md-6">
            <h2>Thêm nhóm</h2>
            <hr />
            <form asp-controller="NewOption" asp-action="IndexTeam" method="post" >
                <div class="form-group">
                    <input type="text" name="Name" class="form-control" placeholder="Vui lòng nhập tên nhóm" required />
                </div>  
                <div class="form-group">
                    <input type="hidden" name="TeamCode" id="sourceCodeInput" class="form-control" />   
                </div>
                <div class="form-group">
                    <button type="submit"class="btn btn-primary">Thêm</button>
                </div>
            </form>

        </div>
    </div>
    
</div>
</body>
<script>
    function generateSourceCode() {
        var sourceCodeInput = document.getElementById("sourceCodeInput");
        var generatedCode = generateUniqueCode();
        console.log("After setting value:", sourceCodeInput.value);
        sourceCodeInput.value = generatedCode;
    }

    var generatedCodes = [];

    function generateUniqueCode() {
        var min = 1;
        var max = 10000000;

        var uniqueCode;
        do {
            uniqueCode = Math.floor(Math.random() * (max - min + 1)) + min;
        } while (generatedCodes.includes(uniqueCode));

        generatedCodes.push(uniqueCode);

        return uniqueCode;
    }

</script>